version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: agile-poker-db
    environment:
      POSTGRES_DB: agile_poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Stella04
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  pgdata:

networks:
  springboot-network:


